//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("livesModel", "FK_CategoriaSubcategoria", "Categoria", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BO.Categoria), "Subcategoria", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BO.Subcategoria))]
[assembly: EdmRelationshipAttribute("livesModel", "FK_EstadoVideoVideo", "EstadoVideo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BO.EstadoVideo), "Video", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BO.Video))]
[assembly: EdmRelationshipAttribute("livesModel", "SubcategoriaVideo", "Subcategoria", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BO.Subcategoria), "Video", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BO.Video))]

#endregion

namespace BO
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Categoria> Categoria
        {
            get
            {
                if ((_Categoria == null))
                {
                    _Categoria = base.CreateObjectSet<Categoria>("Categoria");
                }
                return _Categoria;
            }
        }
        private ObjectSet<Categoria> _Categoria;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EstadoVideo> EstadoVideo
        {
            get
            {
                if ((_EstadoVideo == null))
                {
                    _EstadoVideo = base.CreateObjectSet<EstadoVideo>("EstadoVideo");
                }
                return _EstadoVideo;
            }
        }
        private ObjectSet<EstadoVideo> _EstadoVideo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Subcategoria> Subcategoria
        {
            get
            {
                if ((_Subcategoria == null))
                {
                    _Subcategoria = base.CreateObjectSet<Subcategoria>("Subcategoria");
                }
                return _Subcategoria;
            }
        }
        private ObjectSet<Subcategoria> _Subcategoria;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Video> Video
        {
            get
            {
                if ((_Video == null))
                {
                    _Video = base.CreateObjectSet<Video>("Video");
                }
                return _Video;
            }
        }
        private ObjectSet<Video> _Video;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categoria EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategoria(Categoria categoria)
        {
            base.AddObject("Categoria", categoria);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EstadoVideo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEstadoVideo(EstadoVideo estadoVideo)
        {
            base.AddObject("EstadoVideo", estadoVideo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Subcategoria EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSubcategoria(Subcategoria subcategoria)
        {
            base.AddObject("Subcategoria", subcategoria);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Video EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVideo(Video video)
        {
            base.AddObject("Video", video);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="livesModel", Name="Categoria")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Categoria : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Categoria object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="nome">Initial value of the nome property.</param>
        public static Categoria CreateCategoria(global::System.Int32 id, global::System.String nome)
        {
            Categoria categoria = new Categoria();
            categoria.id = id;
            categoria.nome = nome;
            return categoria;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("livesModel", "FK_CategoriaSubcategoria", "Subcategoria")]
        public EntityCollection<Subcategoria> Subcategorias
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Subcategoria>("livesModel.FK_CategoriaSubcategoria", "Subcategoria");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Subcategoria>("livesModel.FK_CategoriaSubcategoria", "Subcategoria", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="livesModel", Name="EstadoVideo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EstadoVideo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EstadoVideo object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="estado">Initial value of the estado property.</param>
        public static EstadoVideo CreateEstadoVideo(global::System.Int32 id, global::System.String estado)
        {
            EstadoVideo estadoVideo = new EstadoVideo();
            estadoVideo.id = id;
            estadoVideo.estado = estado;
            return estadoVideo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.String _estado;
        partial void OnestadoChanging(global::System.String value);
        partial void OnestadoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("livesModel", "FK_EstadoVideoVideo", "Video")]
        public EntityCollection<Video> Videos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Video>("livesModel.FK_EstadoVideoVideo", "Video");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Video>("livesModel.FK_EstadoVideoVideo", "Video", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="livesModel", Name="Subcategoria")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Subcategoria : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Subcategoria object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="nome">Initial value of the nome property.</param>
        public static Subcategoria CreateSubcategoria(global::System.Int32 id, global::System.String nome)
        {
            Subcategoria subcategoria = new Subcategoria();
            subcategoria.id = id;
            subcategoria.nome = nome;
            return subcategoria;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("livesModel", "FK_CategoriaSubcategoria", "Categoria")]
        public Categoria Categoria
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("livesModel.FK_CategoriaSubcategoria", "Categoria").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("livesModel.FK_CategoriaSubcategoria", "Categoria").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Categoria> CategoriaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("livesModel.FK_CategoriaSubcategoria", "Categoria");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Categoria>("livesModel.FK_CategoriaSubcategoria", "Categoria", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("livesModel", "SubcategoriaVideo", "Video")]
        public EntityCollection<Video> Videos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Video>("livesModel.SubcategoriaVideo", "Video");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Video>("livesModel.SubcategoriaVideo", "Video", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="livesModel", Name="Video")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Video : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Video object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="descricao">Initial value of the descricao property.</param>
        /// <param name="url">Initial value of the url property.</param>
        /// <param name="data">Initial value of the data property.</param>
        /// <param name="id_user">Initial value of the id_user property.</param>
        /// <param name="titulo">Initial value of the titulo property.</param>
        public static Video CreateVideo(global::System.Int32 id, global::System.String descricao, global::System.String url, global::System.DateTime data, global::System.Guid id_user, global::System.String titulo)
        {
            Video video = new Video();
            video.id = id;
            video.descricao = descricao;
            video.url = url;
            video.data = data;
            video.id_user = id_user;
            video.titulo = titulo;
            return video;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descricao
        {
            get
            {
                return _descricao;
            }
            set
            {
                OndescricaoChanging(value);
                ReportPropertyChanging("descricao");
                _descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descricao");
                OndescricaoChanged();
            }
        }
        private global::System.String _descricao;
        partial void OndescricaoChanging(global::System.String value);
        partial void OndescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime data
        {
            get
            {
                return _data;
            }
            set
            {
                OndataChanging(value);
                ReportPropertyChanging("data");
                _data = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("data");
                OndataChanged();
            }
        }
        private global::System.DateTime _data;
        partial void OndataChanging(global::System.DateTime value);
        partial void OndataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id_user
        {
            get
            {
                return _id_user;
            }
            set
            {
                Onid_userChanging(value);
                ReportPropertyChanging("id_user");
                _id_user = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_user");
                Onid_userChanged();
            }
        }
        private global::System.Guid _id_user;
        partial void Onid_userChanging(global::System.Guid value);
        partial void Onid_userChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String titulo
        {
            get
            {
                return _titulo;
            }
            set
            {
                OntituloChanging(value);
                ReportPropertyChanging("titulo");
                _titulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("titulo");
                OntituloChanged();
            }
        }
        private global::System.String _titulo;
        partial void OntituloChanging(global::System.String value);
        partial void OntituloChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("livesModel", "FK_EstadoVideoVideo", "EstadoVideo")]
        public EstadoVideo Estado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EstadoVideo>("livesModel.FK_EstadoVideoVideo", "EstadoVideo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EstadoVideo>("livesModel.FK_EstadoVideoVideo", "EstadoVideo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EstadoVideo> EstadoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EstadoVideo>("livesModel.FK_EstadoVideoVideo", "EstadoVideo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EstadoVideo>("livesModel.FK_EstadoVideoVideo", "EstadoVideo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("livesModel", "SubcategoriaVideo", "Subcategoria")]
        public EntityCollection<Subcategoria> Subcategorias
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Subcategoria>("livesModel.SubcategoriaVideo", "Subcategoria");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Subcategoria>("livesModel.SubcategoriaVideo", "Subcategoria", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
